// <auto-generated />
using System;
using Andeanpm.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Andeanpm.Server.Data.Migrations
{
    [DbContext(typeof(AndeampDBContext))]
    [Migration("20220927155914_BannerMigration")]
    partial class BannerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Andeanpm.Shared.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplyFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Module = "Our Company",
                            Url = "assets/banners/ourcompany.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Module = "Our People",
                            Url = "assets/banners/ourpeople.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Module = "Careers",
                            Url = "assets/banners/careers.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Module = "Cerro Rico Mine",
                            Url = "assets/banners/cerroricomine.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Module = "Cachi Laguna",
                            Url = "assets/banners/cachilaguna.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Module = "Cerro Rico Deposits",
                            Url = "assets/banners/cerroricodeposits.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Module = "Ore Purchasing",
                            Url = "assets/banners/orepurchasing.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Module = "El Asiento",
                            Url = "assets/banners/elasiento.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Module = "Tatasi Portugalete",
                            Url = "assets/banners/tatasiportugalete.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Module = "Monserrat",
                            Url = "assets/banners/monserrat.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Module = "San Bartolome",
                            Url = "assets/banners/sanbartolome.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Module = "Exploration",
                            Url = "assets/banners/exploration.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Module = "San Pablo",
                            Url = "assets/banners/sanpablo.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Module = "Rio Blanco",
                            Url = "assets/banners/rioblanco.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Module = "Sustainability",
                            Url = "assets/banners/sustainability.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Module = "Esg",
                            Url = "assets/banners/esg.jpg"
                        },
                        new
                        {
                            Id = 17,
                            Module = "Governance",
                            Url = "assets/banners/governance.jpg"
                        },
                        new
                        {
                            Id = 18,
                            Module = "Investors",
                            Url = "assets/banners/investors.jpg"
                        },
                        new
                        {
                            Id = 19,
                            Module = "News",
                            Url = "assets/banners/news.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Module = "Contact",
                            Url = "assets/banners/contact.jpg"
                        },
                        new
                        {
                            Id = 21,
                            Module = "Customer Care",
                            Url = "assets/banners/customercare.jpg"
                        });
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ContactDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNews")
                        .HasColumnType("datetime2");

                    b.Property<string>("PDFURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PKNews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Alberto Morales is founder of Andean Precious Metals Corp, and has over 30 years of experience specialized in corporate finance, mergers and acquisitions and corporate restructurings. He has also participated individually in other private equity and venture capital projects as co-developer, investor and/or advisor in telecommunications, aviation, tourism, financial services and asset management, mining and alternative energy. He has participated in the planning, formation, development and consolidating stages of various start-up business ventures. He holds a Bachelors degree in Law from the University of Monterrey (1984) and a Masters degree in Compared Law from the New York University School of Law (1987), and was admitted to practice law in Mexico in 1985 and in the State of New York in 1989.",
                            PathImage = "assets/our-people/Foto.png",
                            Position = 1,
                            Subtitle = "Founder, Executive Chairman & Director",
                            Team = "Leadership",
                            Title = "ALBERTO MORALES"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Simon Griffiths has extensive global experience in the resources industry and has held senior positions in private and public companies in both developed and emerging economies. He is a Chartered Mining Engineer and Qualified Person (QP) having held senior technical and operational leadership roles. At OceanaGold (TSX/ASX) he was Director of Operations at the Haile Gold mine after leading the technical due diligence for the $480million acquisition. He managed multiple technical studies at Newcrest Mining (ASX), TWSP Ltd and Solid Energy (NZX) for major resource projects in Australia, West Africa, Mozambique, Philippines, Indonesia, New Zealand and USA. Mr. Griffiths has an undergraduate B.Eng degree and Masters in Mining Engineering from Camborne School of Mines and a Masters in Mineral Economics from Curtin Business School, Western Australia. He has championed environmental engineering in mine design, ore reserve governance protocols and re-engineered major mining operations delivering significant valuation uplift",
                            PathImage = "assets/our-people/Simon-Griffiths.png",
                            Position = 2,
                            Subtitle = "President & Chief Executive Officer",
                            Team = "Leadership",
                            Title = "SIMON GRIFFITHS"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Mr. Chan is an experienced financial executive in the mining and healthcare industries, having held senior leadership roles in several Canadian publicly held companies on the TSX, TSX-V and CSE. Most recently, Mr. Chan was the CFO of a privately held cannabinoid technology company. Previously, he served as Interim CFO and Vice President, Finance at Liberty Health Sciences, where he led the growth of its financial operations subsequent to Liberty's spinoff from Aphria Inc., and Vice President, Finance at Orvana Minerals Corp. where he closed several transformational debt financings. Mr. Chan is a Chartered Professional Accountant (CA, CPA) and holds a B.Comm from the University of Toronto.",
                            PathImage = "assets/our-people/Jeff-Chan.png",
                            Position = 3,
                            Subtitle = "Chief Financial Officer",
                            Team = "Leadership",
                            Title = "JEFF CHAN"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Fraser Buchan has been involved in the mining industry since 2006, when he joined the institutional sales desk at GMP Securities in Toronto and then GMP Europe in London. Mr. Buchan has served as an executive of Newcastle Gold, Elgin Mining and Touchstone Gold and has served as a director of several publicly traded resource companies. Most recently, Mr. Buchan co-founded Tradewind Markets in partnership with IEX Group and Sprott Inc. Backed by leading companies in the precious metals industry, Tradewind provides institutions with a suite of digital solutions in trading, supply chain management, settlement and custody of precious metals. Mr. Buchan holds a degree in Economics from McGill University.",
                            PathImage = "assets/our-people/Fraser-Buchan.png",
                            Position = 4,
                            Subtitle = "Corporate Development & Investor Relations",
                            Team = "Leadership",
                            Title = "FRASER BUCHAN"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Ben McCormick has worked in senior roles for multinational corporations in the mining and resources sector for over twenty years. Most recently, he was the General Manager Projects and Chief Financial Officer of Rincon Mining Pty Limited where he was instrumental in the successful turnaround and sale of the Lithium asset in Argentina and the Bicarbonate of Soda asset in Colorado, USA. Prior to joining Rincon, Ben was Group Treasury of Newcrest Mining Ltd (ASX, TSX) and Western Mining Ltd (ASX). Ben holds a Bachelor of Business - Accounting from Monash University, is a Certified Practicing Accountant (CPA), and has extensive experience in Accounting, Treasury, Insurance, M&A, Business Turnaround, Project Management and Supply and logistics",
                            PathImage = "assets/our-people/Humberto-Rada.png",
                            Position = 5,
                            Subtitle = "VP Treasury and Corporate Development",
                            Team = "Leadership",
                            Title = "BEN MCCORMICK"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Mr. Rada Gomez has a degree in Business Administration, Economics and Public Accounting from the Catholic University of Chile. He is a member of the Board of the American Chamber of Commerce of Bolivia and a member of the Consultative Council of the Confederation of Private Entrepreneurs of Bolivia. He was President of the Association of Medium Miners, Director of Radio Fides and Fundación Nuevo Norte. His professional career was widely recognized by national and international institutions as a leader in the application of the best mining practices in relation to the Environment, Social and Business Responsibility, receiving more than 20 business and personal awards.",
                            PathImage = "assets/our-people/BEN-MCCORMICK-MC.png",
                            Position = 1,
                            Subtitle = "President of Manquiri (since July 2008)",
                            Team = "Bolivia Management",
                            Title = "Humberto Rada Gómez"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Dante Rodriguez graduated from the Geology School at the University of San Luis Potosi, Mexico (1985). He has been in the mining industry since 1986 in senior geology and exploration positions including General Manager of the Mining Unit and Vice-President of Explorations. He has worked for Peña Colorada, Minas de San Luis, Goldcorp, Starcore International Mines and was the Operations Manager in Santacruz Silver Mining",
                            PathImage = "assets/our-people/Dante-Rodriguez.png",
                            Position = 2,
                            Subtitle = "Chief Operation Officer of Bolivian Operations",
                            Team = "Bolivia Management",
                            Title = "Dante Rodríguez Montes"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Miguel Torres graduated from the Faculty of Earth Sciences at the Autonomous University of Zacatecas, Mexico in 2004. He has extensive geology and exploration experience and has held Project Manager and Superintendent roles at companies including Gold Corp, Starcore, Oroco Resources and Santacruz Silver Mining",
                            PathImage = "assets/our-people/Miguel-Torrres.png",
                            Position = 3,
                            Subtitle = "General Manager of Manquiri",
                            Team = "Bolivia Management",
                            Title = "Miguel Ángel Torres Herrera"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Milhencka Fischer graduated as an Industrial Engineer from the Engineering National Faculty of Oruro, Bolivia in 2002. She has worked in Environmental management for over 15 years, in industries including mining, hydrocarbons and construction. Over the last 10 years, she has developed her professional career though Environmental Head Positions in Mining. Currently, she oversees compliance of all environmental Bolivian regulation and international regulations",
                            PathImage = "assets/our-people/Milhencka-Fisher.png",
                            Position = 4,
                            Subtitle = "Environmental Manager",
                            Team = "Bolivia Management",
                            Title = "Milhencka Paola Fischer Díaz"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Alberto Morales is founder of Andean Precious Metals Corp, and has over 30 years of experience specialized in corporate finance, mergers and acquisitions and corporate restructurings. He has also participated individually in other private equity and venture capital projects as co-developer, investor and/or advisor in telecommunications, aviation, tourism, financial services and asset management, mining and alternative energy. He has participated in the planning, formation, development and consolidating stages of various start-up business ventures. He holds a Bachelors degree in Law from the University of Monterrey (1984) and a Masters degree in Compared Law from the New York University School of Law (1987), and was admitted to practice law in Mexico in 1985 and in the State of New York in 1989.",
                            PathImage = "",
                            Position = 1,
                            Subtitle = "Founder, Executive Chairman & Director\r\nMember of the Nomination and Corporate Governance Committee",
                            Team = "Board of Directors",
                            Title = "ALBERTO MORALES"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Simon Griffiths has extensive global experience in the resources industry, both public and private companies in developed and emerging economies. He is a Chartered Mining Engineer and Qualified Person (QP) having held senior technical and operational leadership roles. At TSX/ASX listed OceanaGold he was Director of Operations at Haile Gold mine after leading the technical due diligence for the $480million acquisition. At Newcrest Mining (ASX), TWSP Ltd and Solid Energy (NZX) Simon has managed multiple technical studies for major resource projects in Australia, West Africa, Mozambique, Philippines, Indonesia, New Zealand and USA. Mr. Griffiths has an undergraduate B.Eng degree and Masters in Mining Engineering from Camborne School of Mines and a Masters in Mineral Economics from Curtin Business School, Western Australia. He has championed environmental engineering in mine design, ore reserve governance protocols and re-engineered major mining operations delivering significant valuation uplift.",
                            PathImage = "",
                            Position = 2,
                            Subtitle = "Director\r\nPresident & Chief Executive Officer\r\nMember of the Health, Safety, Environment, Social and Sustainability Committee",
                            Team = "Board of Directors",
                            Title = "SIMON GRIFFITHS"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Peter Gundy is the founder of Neo Material Technologies Inc (“NEM”), serving as CEO and chairman from 1992 to 2008. Mr. Gundy created one of Canada’s most successful small/medium enterprises operated by Canadians in China and South East Asia. With manufacturing plants in China and Thailand, NEM became #1 in the world in powerful high-tech magnetic materials for the world’s electronic industries (NEM’s proprietary material was used in every hard drive manufactured). NEM became # 1 globally in the production of advanced rare earths also used in the global electronics industries and automotive sector. In 2012, NEM was sold to Molycorp for $1.1 billion. Mr. Gundy has served as a director with numerous publicly traded companies, including Banro Corp., True Gold Mining Inc., and Clifton Star Resources Corp.",
                            PathImage = "",
                            Position = 3,
                            Subtitle = "Independent Director\r\nChairman of the Audit Committee\r\nChairman of the Nomination And Corporate Governance Committee\r\nMember of the Audit Committee",
                            Team = "Board of Directors",
                            Title = "PETER GUNDY"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Grant Angwin has nearly 40 years’ experience in precious metals. He was, until recently, the President of Asahi Refining NA – the world’s largest gold and silver refiners with 3 manufacturing operations in North America. Prior to the sale of the business in 2015, he worked for Johnson Matthey, both in the UK and USA, where he held various senior management roles. His experience includes being the former Chair of the London Bullion Market Association, past Member of the Shanghai Gold Exchange International Advisory Board and a Board Member of the Silver Institute. He currently sits on the ICE Benchmark Precious Metals Oversight Committee for the LBMA Gold and Silver prices. He studied Chemistry and Business and Finance at the University of Hertfordshire as well as the Executive Management Programme at Queens School of Business, Ontario.",
                            PathImage = "",
                            Position = 4,
                            Subtitle = "Independent Director\r\nChairman of Health, Safety, Environment, Social and Sustainability Committee\r\nMember of the Audit Committee\r\nMember of the Compensation Committee\r\nMember of the Nomination and Corporate Governance Committee",
                            Team = "Board of Directors",
                            Title = "GRANT ANGWIN"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Mr. Felipe Canales has 40 years of experience in the corporate finance and strategy areas, with over 25 years in top executive positions at major public companies. He has personally led and successfully executed large and complex corporate finance transactions, multi-jurisdictional debt restructurings, mergers and acquisitions, joint-ventures, and capital raisings. He is currently Co-CEO at Rose Hill, a Nasdaq SPAC focused on Latin America, among other international advising positions. Mr. Canales was CFO of Axtel, a major Mexican telecom company, from 2009 to 2017. Prior to Axtel he was CFO of Sigma Alimentos, the food division of Alfa, a global Mexican conglomerate with operations in Canada, the United States, Latin America, Europe and Asia, where he held other positions during his 30-year career at that company. Mr. Canales has an MBA degree from the Wharton School at the University of Pennsylvania and a B.Sc. in Industrial Engineering from Instituto Tecnológico de Monterrey.",
                            PathImage = "",
                            Position = 5,
                            Subtitle = "Independent Director\r\nMember of the Audit Committee\r\nMember of the Compensation Committee",
                            Team = "Board of Directors",
                            Title = "FELIPE CANALES"
                        },
                        new
                        {
                            Id = 15,
                            Content = "He graduated from the Universidad Autonoma de Nuevo Leon (UANL) where he obtained his Law Degree with Honorary mention. He also earned a Master's Degree in Finance from the University of Wisconsin and enrolled as an Honor Student. Before joining CEMEX, he was Deputy General Director of Regional Banking, responsible for all aspects (Credit, Legal, etc.) related to the Bank’s operation in its 121 local branches from 1985 to 1987. He joined CEMEX, S.A.B. de C.V., in 1987 and served as General Legal Director until June 2014, when he was promoted to Legal Executive Vice President in 2017. Mr. Villarreal also held the position as a consultant to the Chairman of the Board of Directors and to the CEO of CEMEX, until December 31th, 2017. Furthermore, he served as Secretary of the Board of Directors of CEMEX, from 1995 to 2017. And figured as Secretary of the Board of Directors of CEMEX Mexico until February 2017. Mr. Villarreal has been a member of the Board of Directors of CEMEX, S.A.B. of C.V. since 2017. He is also a member of the Board of Directors of several Companies, such as Grupo Cementos de Chihuahua, S.A. de C.V., Vinte Viviendas Integrales, S.A.B. of C.V., Banco Bancrea, S.A. Institución de Banca Múltiple y Arendal, S. de R.L. de C.V., until February 2012; Mr. Villarreal held the position of Secretary of the Board of Directors of Enseñanza e Investigación Superior, A.C., a company that manages the Instituto Tecnológico y de Estudios Superiores de Monterrey (ITESM).",
                            PathImage = "",
                            Position = 6,
                            Subtitle = "Independent Director\r\nMember of the Nomination and Corporate Governance Committee",
                            Team = "Board of Directors",
                            Title = "RAMIRO VILLARREAL"
                        });
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Maximum")
                        .HasColumnType("bigint");

                    b.Property<long>("Minimum")
                        .HasColumnType("bigint");

                    b.Property<long>("Val")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Maximum = 5500L,
                            Minimum = 1L,
                            Val = 0L
                        },
                        new
                        {
                            Id = 2,
                            Maximum = 12L,
                            Minimum = 1L,
                            Val = 0L
                        },
                        new
                        {
                            Id = 3,
                            Maximum = 65L,
                            Minimum = 10L,
                            Val = 0L
                        },
                        new
                        {
                            Id = 4,
                            Maximum = 280L,
                            Minimum = 50L,
                            Val = 0L
                        },
                        new
                        {
                            Id = 5,
                            Maximum = 60L,
                            Minimum = 1L,
                            Val = 0L
                        });
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsSubscriber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Andeanpm.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 9, 27, 10, 59, 13, 994, DateTimeKind.Local).AddTicks(1131),
                            Email = "cesarv@acsoltec.com",
                            PasswordHash = new byte[] { 123, 250, 31, 165, 226, 189, 161, 46, 113, 9, 177, 52, 107, 70, 229, 38, 197, 249, 211, 168, 192, 10, 115, 209, 118, 86, 206, 135, 54, 83, 71, 216, 74, 165, 52, 60, 61, 136, 180, 84, 243, 217, 74, 186, 195, 39, 83, 212, 97, 133, 209, 125, 35, 37, 60, 169, 171, 211, 126, 179, 189, 125, 99, 238 },
                            PasswordSalt = new byte[] { 187, 48, 80, 113, 76, 183, 101, 60, 62, 84, 195, 159, 25, 33, 109, 27, 197, 31, 2, 117, 206, 248, 84, 224, 168, 126, 121, 176, 59, 157, 234, 204, 212, 153, 43, 103, 80, 210, 171, 57, 187, 178, 205, 230, 154, 197, 118, 5, 213, 249, 211, 75, 189, 208, 247, 216, 21, 71, 23, 117, 7, 201, 56, 106, 9, 43, 93, 58, 26, 213, 87, 153, 109, 41, 145, 193, 46, 203, 102, 197, 89, 201, 84, 36, 53, 137, 94, 84, 68, 202, 120, 26, 255, 227, 122, 238, 128, 95, 246, 30, 175, 100, 56, 160, 159, 58, 73, 198, 247, 147, 10, 228, 70, 27, 91, 21, 242, 76, 167, 13, 162, 66, 70, 46, 147, 140, 187, 170 },
                            Role = "Admi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
